### ISSUE TITLE
Slicing and selecting data via schema.yml

### ISSUE THREAD

**Issue by vhalli** [jaidevd/pysemantic#37]
First 1000 rows. Current functionality.
nrows: 1000
- [x] 1000 randomly selected rows.
  nrows:
  N: 1000
  random: True
- [x] 1000 randomly selected rows between 30000 and 50000
  nrows:
  N: 1000
  random: True
  start: 30000
  stop: 50000
- [x] All rows between row 50 and row 100.
  nrows:
  start: 50
  stop: 100
- [x] All rows for which callable returns true.
  nrows:
  N: callable

**Comment by jaidevd** [comment]
Closed in 14b6becabdd16971bd91df1d7ac06863b0374c30
